#=========Enchantments=========#
#PROTECTION_ENVIRONMENTAL
#PROTECTION_FIRE
#PROTECTION_FALL
#PROTECTION_EXPLOSIONS
#ROTECTION_PROJECTILE
#OXYGEN
#WATER_WORKER
#DAMAGE_ALL
#DAMAGE_UNDEAD
#DAMAGE_ARTHROPODS
#KNOCKBACK
#FIRE_ASPECT
#LOOT_BONUS_MOBS
#DIG_SPEED
#SILK_TOUCH
#DURABILITY
#LOOT_BONUS_BLOCKS
#ARROW_DAMAGE
#ARROW_KNOCKBACK
#ARROW_FIRE
#ARROW_INFINITE
Settings:
  Prefix: '&8[&bCrazyCrates&8]: '
  InventoryName: '&b&lCrazy &4&lCrates'
  InventorySize: 27
  NoKeyMsg: '&cYou must have a %Key% &cin your hand to use that Crate.'
  AlreadyOpeningCrateMsg: '&cYou are already opening a crate.'
  WorldDisabledMsg: '&cI am sorry but crates are disabled in %World%.'
  QuadCrate:
    ToCloseToAnotherPlayer: '&cYou are to close to a player that is opening their Crate.'
    NeedsMoreRoom: '&cThere is not enough space to open that here.'
  DisabledWorlds:
    - 'world_nether'